import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { Provider } from "@/components/ui/provider"

import { Roboto, MuseoModerno, Inter, Lato } from 'next/font/google';

const inter = Inter({
    subsets: ['latin'], // Specify the character sets you need
    weight: ['200', '400', '700'], // Specify the weights you need
    variable: '--font-inter', // Optional: Define a CSS variable name
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`h-full ${inter.className}`} suppressHydrationWarning>
            <head>
                {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" /> */}
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-white`}
            >
                <Provider>
                    {children}
                </Provider>
            </body>
        </html>
    );
}
